# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buyer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62uyer.proto\x12\tecommerce\"8\n\x12RateProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0e\n\x06rating\x18\x02 \x01(\x05\"%\n\x13RateProductResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2U\n\x05\x42uyer\x12L\n\x0bRateProduct\x12\x1d.ecommerce.RateProductRequest\x1a\x1e.ecommerce.RateProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'buyer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RATEPRODUCTREQUEST']._serialized_start=26
  _globals['_RATEPRODUCTREQUEST']._serialized_end=82
  _globals['_RATEPRODUCTRESPONSE']._serialized_start=84
  _globals['_RATEPRODUCTRESPONSE']._serialized_end=121
  _globals['_BUYER']._serialized_start=123
  _globals['_BUYER']._serialized_end=208
# @@protoc_insertion_point(module_scope)
