# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notify.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import shared_pb2 as shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cnotify.proto\x12\tecommerce\x1a\x0cshared.proto\"\x16\n\x14NotificationResponse\"\xae\x01\n\x0cNotification\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x14\n\x0cproduct_name\x18\x03 \x01(\t\x12%\n\x08\x63\x61tegory\x18\x04 \x01(\x0e\x32\x13.ecommerce.Category\x12\x0c\n\x04\x64\x65sc\x18\x05 \x01(\t\x12\x0b\n\x03qty\x18\x06 \x01(\x05\x12\x0e\n\x06rating\x18\x07 \x01(\x01\x12\x13\n\x0bseller_addr\x18\x08 \x01(\t2V\n\x06Notify\x12L\n\x10SendNotification\x12\x17.ecommerce.Notification\x1a\x1f.ecommerce.NotificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOTIFICATIONRESPONSE']._serialized_start=41
  _globals['_NOTIFICATIONRESPONSE']._serialized_end=63
  _globals['_NOTIFICATION']._serialized_start=66
  _globals['_NOTIFICATION']._serialized_end=240
  _globals['_NOTIFY']._serialized_start=242
  _globals['_NOTIFY']._serialized_end=328
# @@protoc_insertion_point(module_scope)
