# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: register_seller.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15register_seller.proto\x12\tecommerce\"\"\n\rSellerRequest\x12\x11\n\tseller_id\x18\x01 \x01(\t\"\"\n\x10RegisterResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2S\n\x0eRegisterSeller\x12\x41\n\x08Register\x12\x18.ecommerce.SellerRequest\x1a\x1b.ecommerce.RegisterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'register_seller_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SELLERREQUEST']._serialized_start=36
  _globals['_SELLERREQUEST']._serialized_end=70
  _globals['_REGISTERRESPONSE']._serialized_start=72
  _globals['_REGISTERRESPONSE']._serialized_end=106
  _globals['_REGISTERSELLER']._serialized_start=108
  _globals['_REGISTERSELLER']._serialized_end=191
# @@protoc_insertion_point(module_scope)
