# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: word_count.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10word_count.proto\x12\twordcount\"\x1a\n\nMapRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"1\n\x0bMapResponse\x12\"\n\x05pairs\x18\x01 \x03(\x0b\x32\x13.wordcount.KeyValue\"3\n\rReduceRequest\x12\"\n\x05pairs\x18\x01 \x03(\x0b\x32\x13.wordcount.KeyValue\"v\n\x0eReduceResponse\x12\x35\n\x06\x63ounts\x18\x01 \x03(\x0b\x32%.wordcount.ReduceResponse.CountsEntry\x1a-\n\x0b\x43ountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t2\x86\x01\n\tWordCount\x12\x38\n\x03Map\x12\x15.wordcount.MapRequest\x1a\x16.wordcount.MapResponse\"\x00\x30\x01\x12?\n\x06Reduce\x12\x18.wordcount.ReduceRequest\x1a\x19.wordcount.ReduceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'word_count_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REDUCERESPONSE_COUNTSENTRY']._options = None
  _globals['_REDUCERESPONSE_COUNTSENTRY']._serialized_options = b'8\001'
  _globals['_MAPREQUEST']._serialized_start=31
  _globals['_MAPREQUEST']._serialized_end=57
  _globals['_MAPRESPONSE']._serialized_start=59
  _globals['_MAPRESPONSE']._serialized_end=108
  _globals['_REDUCEREQUEST']._serialized_start=110
  _globals['_REDUCEREQUEST']._serialized_end=161
  _globals['_REDUCERESPONSE']._serialized_start=163
  _globals['_REDUCERESPONSE']._serialized_end=281
  _globals['_REDUCERESPONSE_COUNTSENTRY']._serialized_start=236
  _globals['_REDUCERESPONSE_COUNTSENTRY']._serialized_end=281
  _globals['_KEYVALUE']._serialized_start=283
  _globals['_KEYVALUE']._serialized_end=321
  _globals['_WORDCOUNT']._serialized_start=324
  _globals['_WORDCOUNT']._serialized_end=458
# @@protoc_insertion_point(module_scope)
