# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\x12\x04RAFT\"!\n\x12QueryServerRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"G\n\x13QueryServerResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x32L\n\x06\x43lient\x12\x42\n\x0bQueryServer\x12\x18.RAFT.QueryServerRequest\x1a\x19.RAFT.QueryServerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUERYSERVERREQUEST']._serialized_start=22
  _globals['_QUERYSERVERREQUEST']._serialized_end=55
  _globals['_QUERYSERVERRESPONSE']._serialized_start=57
  _globals['_QUERYSERVERRESPONSE']._serialized_end=128
  _globals['_CLIENT']._serialized_start=130
  _globals['_CLIENT']._serialized_end=206
# @@protoc_insertion_point(module_scope)
