# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnode.proto\x12\x04RAFT\"g\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"d\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08voter_id\x18\x02 \x01(\t\x12\x14\n\x0cvote_granted\x18\x03 \x01(\x08\x12\x17\n\x0fold_lease_timer\x18\x04 \x01(\x01\"%\n\x08LogEntry\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x05\"\xa9\x01\n\x11LogRequestRequest\x12\x11\n\tleader_id\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x12\n\nprefix_len\x18\x03 \x01(\x05\x12\x13\n\x0bprefix_term\x18\x04 \x01(\x05\x12\x15\n\rleader_commit\x18\x05 \x01(\x05\x12\x1e\n\x06suffix\x18\x06 \x03(\x0b\x32\x0e.RAFT.LogEntry\x12\x13\n\x0blease_timer\x18\x07 \x01(\x01\"U\n\x12LogRequestResponse\x12\x13\n\x0b\x66ollower_id\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x0b\n\x03\x61\x63k\x18\x03 \x01(\x05\x12\x0f\n\x07success\x18\x04 \x01(\x08\x32\x8b\x01\n\x04Node\x12\x42\n\x0bRequestVote\x12\x18.RAFT.RequestVoteRequest\x1a\x19.RAFT.RequestVoteResponse\x12?\n\nLogRequest\x12\x17.RAFT.LogRequestRequest\x1a\x18.RAFT.LogRequestResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTVOTEREQUEST']._serialized_start=20
  _globals['_REQUESTVOTEREQUEST']._serialized_end=123
  _globals['_REQUESTVOTERESPONSE']._serialized_start=125
  _globals['_REQUESTVOTERESPONSE']._serialized_end=225
  _globals['_LOGENTRY']._serialized_start=227
  _globals['_LOGENTRY']._serialized_end=264
  _globals['_LOGREQUESTREQUEST']._serialized_start=267
  _globals['_LOGREQUESTREQUEST']._serialized_end=436
  _globals['_LOGREQUESTRESPONSE']._serialized_start=438
  _globals['_LOGREQUESTRESPONSE']._serialized_end=523
  _globals['_NODE']._serialized_start=526
  _globals['_NODE']._serialized_end=665
# @@protoc_insertion_point(module_scope)
